/*
==============================================================================

View model Hands

==============================================================================
*/

$modelname ..\custom\fewes_hands\models\weapons/v_hands.mdl
$cdmaterials models/Weapons/v_hand 

$body studio "reference.smd"

$origin 0 13 68
$sequence admire "admire" fps 30 activity ACT_VM_IDLE 1
$sequence ref "reference.smd" fps 30
